### ISSUE TITLE
Could you please specify this repo license?

### ISSUE THREAD

**Issue by noomz** [vruizext/InvertedIndex#1]
I saw no license on this repo files, so depend on https://help.github.com/articles/licensing-a-repository/ this repo should be copyright.

```text
However, without a license, the default copyright laws apply
``` 

If you don't intend to make it copyright, I think we need `LICENSE.txt` so the community can fork and use it the right way :D

**Comment by vruizext** [comment]
Hey, thanks for the heads up and sorry for the late answer. I've decided to use Apache License.
